/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class KasirPageUser extends javax.swing.JFrame {

    UserProfile p;
    
    
    /**
     * Creates new form AdminPage1
     */
    public KasirPageUser() {
        initComponents();
    }

    public KasirPageUser(UserProfile P) {
        initComponents();
        
        viewData("");
         
        
    }      
         
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelDataUser = new javax.swing.JLabel();
        labelDataProduk = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTambahUser = new javax.swing.JButton();
        txtUbahUser = new javax.swing.JButton();
        txtHapusUser = new javax.swing.JButton();
        txtRefreshUser = new javax.swing.JButton();
        txtCariUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        labelCariUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconKeluar = new javax.swing.JLabel();
        iconProfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataUser.setText("Data User");
        jPanel2.add(labelDataUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, -1, 28));

        labelDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataProduk.setForeground(new java.awt.Color(255, 255, 255));
        labelDataProduk.setText("Data Produk");
        labelDataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataProdukMouseClicked(evt);
            }
        });
        jPanel2.add(labelDataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 6, -1, 28));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtTambahUser.setBackground(new java.awt.Color(102, 102, 255));
        txtTambahUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTambahUser.setForeground(new java.awt.Color(255, 255, 255));
        txtTambahUser.setText("Tambah");
        txtTambahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahUserActionPerformed(evt);
            }
        });

        txtUbahUser.setBackground(new java.awt.Color(102, 102, 255));
        txtUbahUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUbahUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUbahUser.setText("Ubah");
        txtUbahUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbahUserActionPerformed(evt);
            }
        });

        txtHapusUser.setBackground(new java.awt.Color(102, 102, 255));
        txtHapusUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtHapusUser.setForeground(new java.awt.Color(255, 255, 255));
        txtHapusUser.setText("Hapus");
        txtHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHapusUserActionPerformed(evt);
            }
        });

        txtRefreshUser.setBackground(new java.awt.Color(102, 102, 255));
        txtRefreshUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtRefreshUser.setForeground(new java.awt.Color(255, 255, 255));
        txtRefreshUser.setText("Refresh");
        txtRefreshUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefreshUserActionPerformed(evt);
            }
        });

        txtCariUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariUserKeyReleased(evt);
            }
        });

        Tabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "ID", "FULLNAME", "USERNAME", "PASSWORD", "LEVEL"
            }
        ));
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        labelCariUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUbahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRefreshUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCariUser)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTambahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUbahUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHapusUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRefreshUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCariUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 940, 460));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KASIR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        iconKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_30px.png"))); // NOI18N
        iconKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconKeluarMouseClicked(evt);
            }
        });
        jPanel1.add(iconKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 30, 40));

        iconProfil.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        iconProfil.setForeground(new java.awt.Color(255, 255, 255));
        iconProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/male_user_40px.png"))); // NOI18N
        iconProfil.setText("Satrio");
        jPanel1.add(iconProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked

    }//GEN-LAST:event_Tabel1MouseClicked

    private void txtTambahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahUserActionPerformed
        TambahData T = new TambahData(this, true);
        T.setVisible(true);
    }//GEN-LAST:event_txtTambahUserActionPerformed

    private void txtCariUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariUserKeyReleased
        String key = txtCariUser.getText();
        String w = "WHERE "
                + "fullname LIKE '%"+key+"%' "
                + "OR username LIKE '%"+key+"%' "
                + "OR password LIKE '%"+key+"%' "
                + "OR level LIKE '%"+key+"%'";
        viewData(w);
    }//GEN-LAST:event_txtCariUserKeyReleased

    private void txtRefreshUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefreshUserActionPerformed
        txtCariUser.setText(""); 
        viewData(""); 
    }//GEN-LAST:event_txtRefreshUserActionPerformed

    private void txtHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusUserActionPerformed
        int n = Tabel1.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(Tabel1.getValueAt(n, 0).toString());
//            JOptionPane.showMessageDialog(this, id); 
            
            int pilihan = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin untuk menghapus data user ini?",
                    "Hapus Data",JOptionPane.YES_NO_OPTION);
            if(pilihan == 0){
                String Q = "DELETE FROM akun WHERE id="+id+" ";
                try {
                    Connection K = Koneksi.conn();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewData(""); 
                } catch (Exception e) {
                }
            }else {
                
            }
           
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data"); 
        
        }
    }//GEN-LAST:event_txtHapusUserActionPerformed

    private void txtUbahUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbahUserActionPerformed
        int n = Tabel1.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(Tabel1.getValueAt(n, 0).toString());
            String FN = Tabel1.getValueAt(n, 2).toString();
            String US = Tabel1.getValueAt(n, 3).toString();
            String PS = Tabel1.getValueAt(n, 4).toString();
            String LV = Tabel1.getValueAt(n, 5).toString();
            UbahData U = new UbahData(this, true);
            U.setId(id);
            U.setFN(FN);
            U.setUS(US);
            U.setPS(PS);
            U.setLV(LV);
            U.setVisible(true); 
        }
    }//GEN-LAST:event_txtUbahUserActionPerformed

    private void iconKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKeluarMouseClicked
        keluar();
    }//GEN-LAST:event_iconKeluarMouseClicked

    private void labelDataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataProdukMouseClicked
        AdminPageProduk frame = new AdminPageProduk(); 
        frame.setVisible(true);               
        frame.setLocationRelativeTo(null);    

        dispose();
    }//GEN-LAST:event_labelDataProdukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirPageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable Tabel1;
    private javax.swing.JLabel iconKeluar;
    private javax.swing.JLabel iconProfil;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCariUser;
    private javax.swing.JLabel labelDataProduk;
    private javax.swing.JLabel labelDataUser;
    private javax.swing.JTextField txtCariUser;
    private javax.swing.JButton txtHapusUser;
    private javax.swing.JButton txtRefreshUser;
    private javax.swing.JButton txtTambahUser;
    private javax.swing.JButton txtUbahUser;
    // End of variables declaration//GEN-END:variables

    public static void viewData(String where) {
        try {
            DefaultTableModel m = (DefaultTableModel) Tabel1.getModel();
            m.getDataVector().removeAllElements();
            Connection K = Koneksi.conn();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM akun "+where;
            ResultSet R = S.executeQuery(Q);
            int n = 1;
            while (R.next()) {                 
                int id = R.getInt("id");
                String fullname = R.getString("fullname");
                String username = R.getString("username");
                String password = R.getString("password");
                String level = R.getString("level");
                Object[] data = {id, n, fullname, username, password, level};
                m.addRow(data); 
                n++;
            }
            
            Tabel1.getColumnModel().getColumn(0).setMinWidth(0);
            Tabel1.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (Exception e) {
            //error handling
        }
    }
    
    private void keluar() {
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();
        
        Login loginForm = new Login();
        loginForm.setVisible(true);
        }
    }
}
