/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static main.AdminPageUser.viewData;

/**
 *
 * @author ASUS
 */
public class LaporanKeuangan extends javax.swing.JFrame {

    DataProduk p;
    
    /**
     * Creates new form AdminPage1
     */
    DefaultTableModel model2;
    public LaporanKeuangan() {
        initComponents();
    }
    
    public LaporanKeuangan(DataProduk P) {
        initComponents();
        
         
        
    } 

         
         
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelDataUser = new javax.swing.JLabel();
        labelDataProduk = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTambahProduk3 = new javax.swing.JButton();
        btnTambahProduk2 = new javax.swing.JButton();
        labelDataProduk1 = new javax.swing.JLabel();
        labelDataProduk2 = new javax.swing.JLabel();
        iconKeluar = new javax.swing.JLabel();
        iconProfil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDataUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataUser.setForeground(new java.awt.Color(255, 255, 255));
        labelDataUser.setText("Data User");
        labelDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataUserMouseClicked(evt);
            }
        });
        jPanel2.add(labelDataUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, -1, 28));

        labelDataProduk.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataProduk.setText("Laporan");
        labelDataProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataProdukMouseClicked(evt);
            }
        });
        jPanel2.add(labelDataProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Total Transaksi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total Pendapatan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Tanggal");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner1, "dd-MMM-yyyy"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnTambahProduk3.setBackground(new java.awt.Color(102, 102, 255));
        btnTambahProduk3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTambahProduk3.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahProduk3.setText("Cetak Laporan");
        btnTambahProduk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProduk3ActionPerformed(evt);
            }
        });

        btnTambahProduk2.setBackground(new java.awt.Color(102, 102, 255));
        btnTambahProduk2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnTambahProduk2.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahProduk2.setText("Kembali");
        btnTambahProduk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProduk2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahProduk3)
                .addGap(18, 18, 18)
                .addComponent(btnTambahProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahProduk3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 420));

        labelDataProduk1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataProduk1.setForeground(new java.awt.Color(255, 255, 255));
        labelDataProduk1.setText("Data Produk");
        labelDataProduk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataProduk1MouseClicked(evt);
            }
        });
        jPanel2.add(labelDataProduk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 6, -1, 28));

        labelDataProduk2.setBackground(new java.awt.Color(255, 255, 255));
        labelDataProduk2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelDataProduk2.setForeground(new java.awt.Color(255, 255, 255));
        labelDataProduk2.setText("Pembelian");
        labelDataProduk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataProduk2MouseClicked(evt);
            }
        });
        jPanel2.add(labelDataProduk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -2, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 940, -1));

        iconKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_30px.png"))); // NOI18N
        iconKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconKeluarMouseClicked(evt);
            }
        });
        jPanel1.add(iconKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 30, 40));

        iconProfil.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        iconProfil.setForeground(new java.awt.Color(255, 255, 255));
        iconProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/male_user_40px.png"))); // NOI18N
        iconProfil.setText("Satrio");
        jPanel1.add(iconProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KASIR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKeluarMouseClicked

    }//GEN-LAST:event_iconKeluarMouseClicked

    private void labelDataProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataProdukMouseClicked
       
    }//GEN-LAST:event_labelDataProdukMouseClicked

    private void labelDataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataUserMouseClicked
        AdminPageUser frame = new AdminPageUser(); 
        frame.setVisible(true);               
        frame.setLocationRelativeTo(null);    

        dispose();
    }//GEN-LAST:event_labelDataUserMouseClicked

    private void labelDataProduk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataProduk1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDataProduk1MouseClicked

    private void labelDataProduk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataProduk2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDataProduk2MouseClicked

    private void btnTambahProduk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProduk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahProduk3ActionPerformed

    private void btnTambahProduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProduk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahProduk2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahProduk2;
    private javax.swing.JButton btnTambahProduk3;
    private javax.swing.JLabel iconKeluar;
    private javax.swing.JLabel iconProfil;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelDataProduk;
    private javax.swing.JLabel labelDataProduk1;
    private javax.swing.JLabel labelDataProduk2;
    private javax.swing.JLabel labelDataUser;
    // End of variables declaration//GEN-END:variables

}
